#!/usr/bin/env python3
"""
Setup script for YOLO Model Comparison System
"""

import os
import sys
from pathlib import Path

def install_dependencies():
    """Install required dependencies."""
    print("Installing dependencies...")
    
    # Install Python dependencies
    os.system("pip install -r requirements.txt")
    
    # Create necessary directories
    directories = [
        "models", "data/images", "data/annotations", "data/results", 
        "data/visualizations", "weights", "logs", "configs"
    ]
    
    for directory in directories:
        Path(directory).mkdir(parents=True, exist_ok=True)
        print(f"Created directory: {directory}")
    
    print("Dependencies installed successfully!")

def download_sample_data():
    """Download sample data for testing."""
    print("Setting up sample data...")
    
    # Create sample images directory
    sample_dir = Path("data/sample_images")
    sample_dir.mkdir(parents=True, exist_ok=True)
    
    # Note: In a real implementation, this would download actual COCO validation images
    # For now, we'll use placeholder images that will be generated by the main script
    
    print("Sample data setup completed!")

def setup_environment():
    """Set up the environment for the comparison system."""
    print("Setting up YOLO Model Comparison System...")
    
    # Install dependencies
    install_dependencies()
    
    # Download sample data
    download_sample_data()
    
    # Create __init__.py files
    init_dirs = ["models", "utils"]
    for init_dir in init_dirs:
        init_file = Path(init_dir) / "__init__.py"
        if not init_file.exists():
            init_file.touch()
            print(f"Created {init_file}")
    
    print("\nSetup completed successfully!")
    print("You can now run the comparison system with:")
    print("  python main.py")
    print("  python main.py --help  # for more options")

if __name__ == "__main__":
    setup_environment()